const PUBLIC_KEY_COPY_REQUEST_CHANNEL = 'public-key-copy-request';
const PUBLIC_KEY_COPY_RESPONSE_CHANNEL = 'public-key-copy-response';

const ADD_KEYS_PERMISSION_RESULT_CHANNEL = 'add-keys-permission-result';
const BASIC_INFO_PERMISSION_RESULT_CHANNEL = 'basic-info-permission-result';

module.exports = {
  PUBLIC_KEY_COPY_REQUEST_CHANNEL,
  PUBLIC_KEY_COPY_RESPONSE_CHANNEL,
  ADD_KEYS_PERMISSION_RESULT_CHANNEL,
  BASIC_INFO_PERMISSION_RESULT_CHANNEL,
};
